# Generated by Django 5.1.3 on 2024-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mashina", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mashina",
            name="ishlab_chiqarilgan_yili",
            field=models.CharField(max_length=10),
        ),
    ]
